---
version: '3.8'
services:
  ruby-1-9-3:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: 1.9.3
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-1.9.3.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-1.9.3.rb
  ruby-2-0:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.0'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.0.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.0.rb
  ruby-2-1:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.1'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.1.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.1.rb
  ruby-2-2:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.2'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.2.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.2.rb
  ruby-2-3:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.3'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.3.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.3.rb
  ruby-2-4:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.4'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.4.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.4.rb
  ruby-2-5:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.5'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.5.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.5.rb
  ruby-2-6:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.6'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.6.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.6.rb
  ruby-2-7:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.7'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.7.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-2.7.rb
  ruby-3-0:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '3.0'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.0.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.0.rb
  ruby-3-1:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '3.1'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.1.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.1.rb
  ruby-3-2:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '3.2'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.2.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.2.rb
  ruby-3-3:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '3.3'
        BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.3.rb
    volumes:
    - ".:/app"
    working_dir: "/app"
    environment:
      BUNDLE_GEMFILE: gemfiles/Gemfile.ruby-3.3.rb
