name: Ruby tests

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/Gemfile.ruby-${{ matrix.ruby }}.rb"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "1.9.3"
          - "2.0.0"
          - "2.1.10"
          - "2.2.10"
          - "2.3.8"
          - "2.4.10"
          - "2.5.9"
          - "2.6.10"
          - "2.7.8"
          - "3.0.6"
          - "3.1.4"
          - "3.2.2"
          - "3.3.0-preview2"
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - run: bundle --jobs 8 --retry 3
      - run: bundle exec rake test

  test-old-os:
    runs-on: ubuntu-20.04
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/Gemfile.ruby-${{ matrix.ruby }}.rb"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.2" # This segfaults on 22.04 </shrug>
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - run: bundle --jobs 8 --retry 3
      - run: bundle exec rake test
