name: Ruby tests

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
  pull_request:

jobs:
  test:
    # Ruby 2.2 doesn't install on Ubuntu 22.04, use 20.04 for now
    runs-on: "${{ matrix.ruby == '2.2' && 'ubuntu-20.04' || 'ubuntu-latest' }}"
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/Gemfile.ruby-${{ matrix.ruby }}.rb"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "1.9.3"
          - "2.0.0"
          - "2.1"
          - "2.2"
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - run: bundle --jobs 8 --retry 3
      - run: bundle exec rake test
      - run: bundle exec rake spec
